package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallVipOrder;
import org.linlinjava.litemall.db.domain.LitemallVipOrderExample;

public interface LitemallVipOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int insert(LitemallVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    LitemallVipOrder selectOneByExample(LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    LitemallVipOrder selectOneByExampleSelective(@Param("example") LitemallVipOrderExample example, @Param("selective") LitemallVipOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    List<LitemallVipOrder> selectByExampleSelective(@Param("example") LitemallVipOrderExample example, @Param("selective") LitemallVipOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    List<LitemallVipOrder> selectByExample(LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    LitemallVipOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallVipOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    LitemallVipOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    LitemallVipOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallVipOrder record, @Param("example") LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallVipOrder record, @Param("example") LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallVipOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallVipOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}