package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallVip;
import org.linlinjava.litemall.db.domain.LitemallVipExample;

public interface LitemallVipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    long countByExample(LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int insert(LitemallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int insertSelective(LitemallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    LitemallVip selectOneByExample(LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    LitemallVip selectOneByExampleSelective(@Param("example") LitemallVipExample example, @Param("selective") LitemallVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    List<LitemallVip> selectByExampleSelective(@Param("example") LitemallVipExample example, @Param("selective") LitemallVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    List<LitemallVip> selectByExample(LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    LitemallVip selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallVip.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    LitemallVip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    LitemallVip selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallVip record, @Param("example") LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallVip record, @Param("example") LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallVip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallVipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_vip
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}